name: Deploy to GitHub Pages
on:
  push:
    branches: [main]  # Runs on pushes to main branch
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './'  # Deploys everything in root
      - uses: actions/deploy-pages@v2
